### ISSUE TITLE
Unable to create ESPENI dataset, misplaced suffix?

### ISSUE THREAD

**Issue by kimbauters** [iagw/espeni_raw#1]
Thank you for creating this wonderful dataset!

When trying to recreate the raw ESPENI dataset I ran into a problem. The code fails at line 172: https://github.com/iagw/espeni_raw/blob/3b276bd32c0c4224691b65085059d24a90d9bca0/espeni_raw.py#L172 and complains that `NGEM_SETTLEMENT_PERIOD` does not exist. I believe that the error is caused by the suffix being defined too late. Instead of defining the NGEM suffix on line 166:
https://github.com/iagw/espeni_raw/blob/3b276bd32c0c4224691b65085059d24a90d9bca0/espeni_raw.py#L166 I believe this should happen just before line 107, when the raw National Grid data is being loaded. This ensures that the parsed CSV files are written with the correct suffix.

I would submit a pull request but I am having a few issues verifying the correctness of the fix. The ESO data for 2008 is no longer available, and recent data points do not perfectly match up. I believe the latter is caused by the embedded data still being revised in the ESO datasets.

**Comment by iagw** [comment]
Thanks Kim, sorry its taken a while to get back to you - and thanks for flagging. In terms of recent data points not matching up - do you mean on the values for embedded generation? if so - then yes - National Grid update these on a regular basis - which does not help when trying to recreate data between researchers. That was one of the reasons behind uploading versions to zenodo - so - it will have a doi and can be referenced at a point in time regardless of whether the National Grid updates values (which they regularly do).
On the original point on the NGEM suffix throwing an error, i have fixed it - it works on my local machine and hope it now does for you too. There were a few other issues later on - and I've fixed them too.
Also - the masterdatetime file (for mapping settlement date and settlement period across to utc and localtime) is now autromatically downloaded from github as a parquet file - this should be pretty quick - and is useable for any settlement date, settlement period data that is looking to be mapped to a datetime.
Hope it all works for you now - and again - thanks for flagging.

**Comment by kimbauters** [comment]
No worries at all, we are all busy! 

Yes, the recent data points are indeed because the National Grid hadn't updated them yet. The issue is not related to the ESPENI dataset, it just made it hard(er) to validate the correctness of my own fix. As you mentioned, the DOI records on Zenodo are a great help to provide consistency. There were two main reasons to try to create the ESPENI data set from the raw datasets. First, obviously, for the purpose of reproducibility. Second, energy prices are wild and having the latests data gave a better understanding of how everyday effects, such as high winds or sunny days, affect the fuel mix. 

Thanks for going through the rest of the program as well and catching the other issues. I checked the file changes and everything looks fine to me too. The raw ESPENI dataset was created without any issues and without modifications to the current version of the code. Feel free to close this issue!

**Comment by iagw** [comment]
Thanks Kim, glad its working now. I'll close the issue. best wishes, Grant
